#!/bin/sh

DESC="Orbited"
NAME=orbited
DAEMON=/bin/sh
DAEMON_ARGS="/var/www/scraperwiki/uml/twister/orbited.sh -d -s -v ./var"
PIDFILE=./var/run/$NAME.pid

do_start()
{
	mkdir -p ./var/run
	mkdir -p ./var/log
	$DAEMON $DAEMON_ARGS
}

do_stop()
{
	[ -f $PIDFILE ] && {
		kill -TERM `cat $PIDFILE`
		rm -f $PIDFILE
		}
}

case "$1" in
  start)
	do_start
	;;
  stop)
	do_stop
	;;
  restart)
  	do_stop
  	do_start
	;;
  *)
	echo "Usage: orbited {start|stop|restart}" >&2
	;;
esac
