#!/bin/bash
route add default gw 10.0.0.1 eth0 > /dev/null
export RUBYLIB='/home/scraperwiki/ruby/scraperwiki/lib'
export PYTHONPATH='/home/scraperwiki/python'
export PHPPATH='/home/scraperwiki/php:$PHPPATH'
export NODE_PATH='/usr/local/lib/node_modules:/home/scraperwiki/javascript:/home/scriptrunner'
su scriptrunner -c "cd ~;/home/startup/exec.$1 --script=/home/scriptrunner/script.$1"