#! /bin/sh
### BEGIN INIT INFO
# Provides:          scrapers
# Required-Start:    $local_fs
# Default-Start:     2
# Short-Description: Mount scrapers directory
### END INIT INFO

# Author: Mike Richardson <mike@quaking.demon.co.uk>
#

# Do NOT "set -e"

# PATH should only include /usr/* if it runs after the mountnfs.sh script
PATH=/sbin:/usr/sbin:/bin:/usr/bin
DESC="Scrapers"
NAME=scrapers
DAEMON=
DAEMON_ARGS=
PIDFILE=
SCRIPTNAME=
MOUNTS="__MOUNTS__"

# Exit if the package is not installed
# [ -x "$DAEMON" ] || exit 0

# Read configuration variable file if it is present
# [ -r /etc/default/$NAME ] && . /etc/default/$NAME

# Load the VERBOSE setting and other rcS variables
. /lib/init/vars.sh

# Define LSB log_* functions.
# Depend on lsb-base (>= 3.0-6) to ensure that this file is present.
. /lib/lsb/init-functions

#
# Function that starts the daemon/service
#
do_start()
{
	for mount in ${MOUNTS}
	do
		mount -t hostfs `echo $mount | sed 's/\(.*\):\(.*\)/-o\2,ro none \1/'`
	done
}

#
# Function that stops the daemon/service
#
do_stop()
{
	for mount in ${MOUNTS}
	do
		umount `echo $mount | sed 's/\(.*\):\(.*\)/\1/'`
	done
}

#
# Function that sends a SIGHUP to the daemon/service
#
do_reload() {
	:
}

case "$1" in
  start)
	[ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
	do_start
	case "$?" in
		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
	esac
	;;
  stop)
	[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
	do_stop
	case "$?" in
		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
	esac
	;;
  restart|force-reload)
	#
	# If the "reload" option is implemented then remove the
	# 'force-reload' alias
	#
	log_daemon_msg "Restarting $DESC" "$NAME"
	do_stop
	case "$?" in
	  0|1)
		do_start
		case "$?" in
			0) log_end_msg 0 ;;
			1) log_end_msg 1 ;; # Old process is still running
			*) log_end_msg 1 ;; # Failed to start
		esac
		;;
	  *)
	  	# Failed to stop
		log_end_msg 1
		;;
	esac
	;;
  *)
	echo "Usage: $SCRIPTNAME {start|stop|restart|force-reload}" >&2
	exit 3
	;;
esac

:
